### PR TITLE
LPS-173768 Allow the users to define the default utility page for each type in site initializer 

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-173768)

The goal of these changes is to allow the users to define the default utility pages for the different error codes

## Change summary:

* Add code to site initializer extender to set default utility pages for each type of error
* Update test cases
* Change masterclass, team extranet and welcome site initializers

## Test Scenario

* Enable FF feature.flag.LPS-162765=true
* Create a new site based on master class, team extranet or welcome
* 404 utility page is created as default

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

File: portal-kernel/src/com/liferay/layout/utility/page/kernel/constants/LayoutUtilityPageEntryTypesConstants.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
  */
 public class LayoutUtilityPageEntryTypesConstants {
 
-	public static final String LAYOUT = "LAYOUT";
+	public static final String SC_NOT_FOUND = "SC_NOT_FOUND";
```
Comment (jkappler) [inline portal-kernel/src/com/liferay/layout/utility/page/kernel/constants/LayoutUtilityPageEntryTypesConstants.java:22]: @ealonso, changed this like we talked. This will match apaches status code

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
fixing conflicts

**Review by lfbesada — APPROVED** [review]
Perfect as always 😍 Many thanks!

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @alessandromalves, this has kernel changes so it won't be forwarded automatically 😭

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler, would you mind double checking the compile error happens on osb:osb-asah:osb-asah-common? Thanks!

**Comment by jkappler** [comment]
Hi @Tim-Cao, thanks for taking a look. Error is not related to the changes, see:

```
[exec] > Task :dxp:apps:osb:osb-asah:osb-asah-filter-expression-parser:processResources
     [exec] > Task :dxp:apps:osb:osb-asah:osb-asah-filter-expression-parser:classes
     [exec] > Task :dxp:apps:osb:osb-asah:osb-asah-filter-expression-parser:jar
     [exec] /opt/dev/projects/github/com-liferay-osb-asah-private/osb-asah-common/src/main/java/com/liferay/osb/asah/common/repository/impl/BQEventRepositoryImpl.java:1229: error: cannot find symbol
     [exec] 					filter.getAttributeType(), eventAnalysisFilter,
     [exec] 					^
     [exec]   symbol:   variable filter
     [exec]   location: class com.liferay.osb.asah.common.repository.impl.BQEventRepositoryImpl 
```

**Comment by jkappler** [comment]
@Tim-Cao, caused by https://github.com/liferay/com-liferay-osb-asah-private/commit/06e1d741e5e19439e54d170002a783ef52889b60, bad renaming from Brian

**Comment by Tim-Cao** [comment]
Do you mean we could manual forward this one? @jkappler

**Comment by Tim-Cao** [comment]
Thanks @jkappler, Would you mind checking this failed integration test [com.liferay.layout.utility.page.portlet.action.test.ExportImportLayoutUtilityPageTest](https://testray.liferay.com/home/-/testray/case_results/2181021665) ?

**Comment by jkappler** [comment]
Thanks for catching this @Tim-Cao!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129502

**Comment by Tim-Cao** [comment]
ci:close
